name: Build

on:
  push:
    branches: [ dev, main]
  pull_request:
    branches: [ main ]

env:
  dotnet-version: "3.1.x"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action'
      - uses: actions/checkout@v2

      - name: setup-dotnet
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnet-version }}

      - name: build-dotnet
      - run: dotnet-build .

