name: Build

on:
  push:
    branches: [ dev, main]
  pull_request:
    branches: [ main ]

env:
  dotnet-version: "3.1.x"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build-project
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnet-version }}
      - run: dotnet-build .

